version: '3.8'
services:
  mongodb:
    container_name: mongo_ibb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passIbb
    volumes:
      - mongodb_data:/.data/db
    ports:
      - "27018:27017"
volumes:
  mongodb_data: