import {BadRequestException, Injectable, Logger, UploadedFile} from '@nestjs/common';
import {v4 as uuidv4} from 'uuid';
import {ParseFile} from "../decorators/parse-file.decorator";
import {BlobServiceClient, BlockBlobClient} from "@azure/storage-blob";
import * as process from "process";
import {CivilStateEnumV2, StatusEnumV2, UserRolesV2, UserV2} from "../domain/entity/abstractions/user-v2.abstraction";
import * as csv from 'csv-parser';
import * as streamifier from 'streamifier';
import {formatPhoneNumber} from "../../common/validations/telefone";

@Injectable()
export class UploadService {

    constructor() {
    }

    private async getBlobServiceInstance() {
        const connectionString = process.env.CONNECTION_STRING_AZURE;

        const blobClientService = await BlobServiceClient.fromConnectionString(
            connectionString,
        );

        return blobClientService;
    }

    private async getBlobClient(imageName: string, containerName: string): Promise<BlockBlobClient> {
        const blobService = await this.getBlobServiceInstance();
        const containerClient = blobService.getContainerClient(containerName);
        return containerClient.getBlockBlobClient(imageName);
    }


    async uploadFile(@UploadedFile(ParseFile) file): Promise<string> {
        try {
            const fileName = file.originalname.replace(/([^a-zA-Z0-9-._]+)/gi, '-');
            const azureFileName = `${uuidv4()}_${fileName}`;
            let blockBlobClient;

            try {
                blockBlobClient = await this.getBlobClient(
                    azureFileName,
                    process.env.AZURE_CONTAINER_NAME,
                );
            } catch (e) {
                console.log(e);
                throw new BadRequestException('Erro ao obter informações para salvar a imagem');
            }
            const fileUrl = blockBlobClient.url;
            await blockBlobClient.uploadData(file.buffer);
            return fileUrl;
        } catch (e) {
            console.log(e);
            throw e;
        }
    }

    async uploadCsv(@UploadedFile(ParseFile) file): Promise<UserV2[]> {
        Logger.log(``);
        Logger.log(`> [Service][User V2][POST][uploadCsv] - init`);
        try {
            const results: UserV2[] = [];
            const headers = [
                'Nome', 'Ativo', 'Estado Civil', 'CPF', 'Ident', 'Email', 'data nascimento', 'TipoPessoa',
                'DataCasam', 'NomeVinculo', 'DataFalec', 'Falecido', 'Telefone', 'EnderecoCompleto',
                'Bairro', 'Cidade', 'UF', 'Pais', 'CEP', 'Complemento', 'Numero'
            ];

            return new Promise((resolve, reject) => {
                const stream = streamifier.createReadStream(file.buffer)
                    .pipe(csv({headers, skipLines: 1}))
                    .on('data', (data) => {
                        const membro = {
                            nome:  data['Nome'] ? data['Nome'].toString('utf-8') : '',
                            foto: '',
                            cpf: data['CPF'],
                            rg: data['Ident'],
                            email: this.tratarVariosEmails(data['Email']),
                            telefone: this.tratarTelefone(data['Telefone']),
                            dataNascimento: this.tratarDataNascimento(data['data nascimento']),
                            role: UserRolesV2.MEMBRO,
                            status: data['Ativo'] === 'S' ? StatusEnumV2.ativo : StatusEnumV2.inativo,
                            informacoesPessoais: {
                                estadoCivil: this.tratarEstadoCivil(data['Estado Civil']),
                                casamento: {
                                    conjugue: {
                                        id: '',
                                        nome: '',
                                        isMember: false,
                                        isDiacono: false
                                    },
                                    dataCasamento: null,
                                },
                                filhos: [],
                                temFilhos: false,
                            },
                            diacono: {
                                id: '',
                                nome: '',
                                isDiacono: false,
                                isMember: false,
                            },
                            ministerio: [],
                            endereco: {
                                cep: data['CEP'],
                                rua: data['EnderecoCompleto'],
                                numero: data['Numero'],
                                complemento: data['Complemento'] || '',
                                bairro: data['Bairro'],
                                cidade: data['Cidade'],
                                estado: data['UF'],
                                pais: data['Pais'],
                            },
                            ingresso: {
                                data: null,
                                forma: '',
                                local: '',
                            },
                            transferencia: {
                                data: null,
                                motivo: '',
                                local: '',
                            },
                            falecimento: {
                                data: null,
                                motivo: '',
                                local: '',
                            },
                            exclusao: {
                                data: null,
                                motivo: '',
                            },
                            visitas: {
                                motivo: '',
                            },
                            autenticacao: {
                                providersInfo: [],
                            },
                            isDiacono: false,
                            historico: [],
                        };
                        results.push(membro);
                    })
                    .on('end', () => {
                        for (let i = 0; i < results.length; i++) {
                            results[i].nome = this.nomes_ibb[i];
                        }

                        resolve(results)
                    })
                    .on('error', (error) => reject(error));
            });
        } catch (e) {
            Logger.error(e.stack);
            Logger.error(e);
        }
    }

    async deleteObject(fileUrl: string): Promise<string> {
        try {
            const fileName = fileUrl.split('/').pop();
            const blockBlobClient = await this.getBlobClient(
                fileName,
                process.env.AZURE_CONTAINER_NAME,
            );
            const res = await blockBlobClient.deleteIfExists();

            if (res.succeeded) {
                return 'Arquivo excluído!'
            }

            return 'Falha ao excluir o arquivo!'
        } catch (error) {
            console.error(`Erro ao excluir objeto do S3:`, error);
        }
    }

    private tratarEstadoCivil(estadoCivil: string) {
        switch (estadoCivil.split('(a)')[0]) {
            case 'Solteiro':
                return CivilStateEnumV2.solteiro;
            case 'Casado':
                return CivilStateEnumV2.casado;
            case 'Divorciado':
                return CivilStateEnumV2.divorciado;
            case 'Viúvo':
                return CivilStateEnumV2.viuvo;
            case 'Separado':
                return CivilStateEnumV2.separado;
            default:
                return CivilStateEnumV2.solteiro;
        }
    }

    private tratarVariosEmails(emails: string): string {
        if (emails.includes(';')){
            return emails.split(';').map(email => email.trim())[0];
        }
        return emails;
    }

    private tratarTelefone(telefone: string): string {
        if (!telefone) {
            return '';
        }

        // Regex para capturar os formatos esperados e corrigir quando necessário
        const telefoneRegex = /(?:\d-?)(\d{4,5})-(\d{4})/;
        const match = telefone.match(telefoneRegex);

        if (match) {
            // Captura a parte correta do número
            let numeroCorrigido = match[1] + '-' + match[2];

            // Se a primeira parte tiver apenas 4 dígitos, adiciona o '9' na frente
            if (match[1].length === 4) {
                numeroCorrigido = '9' + numeroCorrigido;
            }

            return `(11) ${numeroCorrigido}`;
        }

        return '';
    }

    private tratarDataNascimento(dataNascimento: Date): Date {
        if (!dataNascimento) {
            return new Date('1900-01-01')
        }

        const diaMesAno = dataNascimento.toString().split('T')[0];
        return new Date(`${diaMesAno}T03:00:00.000Z`);
    }

    nomes_ibb = [
        "Wisys Produtos Inteligentes",
        "Adá Saldanha Neves",
        "Adriana de Fátima Gonçalves Lopes Oliveira",
        "Adriana Reis Pinto",
        "Adriana Tagawa Francisco",
        "Adriano Costa Oliveira",
        "Aiede de Souza Silva",
        "Alan Gomes Pereira",
        "Abigail Queiroz de Paula",
        "Aláudio A Cirino",
        "Alberto Veríssimo Filho",
        "Alda A Carvalho Mayorga",
        "Alexandra Mara Gomes Sudano",
        "Alexandre Davis Tagawa",
        "Alexandre do Valle Traldi",
        "Alexandre Lopes",
        "Aline Ferreira Coropos",
        "Alípio Custódio Filho",
        "Amadeu D'Afonseca e Silva Jr",
        "Amanda do Valle Traldi",
        "Amanda Freua Sartori",
        "Aminadab Saldanha",
        "Ana Carolina Rocha Collyer",
        "Ana Cláudia da Silva Gomes Maitino",
        "Ana Cláudia Queiroz de Siqueira",
        "Ana Cristina Bretones",
        "Ana Fabrizia Gomes Caleffi",
        "Ana Lucia da Silva",
        "Ana Luiza Vidal Gil",
        "Ana Maria Costa Oliveira",
        "Anagir Barcellos Georgean",
        "Anderson de Souza Clementino",
        "André Bretones",
        "André Ishida",
        "André Lopes",
        "André Mora Veríssimo",
        "Angela Maria Ferreira Brito",
        "Annelise Costa Oliveira",
        "Antonio Bráulio Rodrigues de Lemos",
        "Antonio Cesário dos Santos",
        "Antonio Gilbran de Lima",
        "Antonio Nunes de Brito",
        "Antranik Cassapian Junior",
        "Armando Manuel da Silva Rio",
        "Armando Teixeira Moura Junior",
        "Armando Traldi",
        "Arnaldo Junqui",
        "Arthur Eduardo Razuk",
        "Aurea Acácio Lemos Moore",
        "Azarias Severino Remigio",
        "Bárbara Aparecida Vargas Vega Carvalhaes",
        "Benedita Prestes de Castro Teixeira",
        "Betty Albernaz de Carvalho Comin",
        "Bruno Padilha Nogueira",
        "Bruno Ruggeri Faustino",
        "Camila Densa",
        "Camila dos Santos Cruz",
        "Camila Manoela Antunes Nogueira",
        "Camila Mora Edelbi Veríssimo",
        "Camila Vitelo do Nascimento",
        "Carla Fernanda Hernández Simonsen",
        "Carlos Alberto Cerávolo",
        "Carlos Alberto Fernandes",
        "Carlos Eduardo Alves Moita",
        "Carlos Jones Benites Schildt",
        "Carmella Castello Varoni",
        "Cassia Bretones de Paula",
        "Célia Maria de Souza Munhoz",
        "Celia Maria Tambellini Vidal Gil",
        "Celina Pacheco de Souza",
        "Celisana Arruda Soares de Camargo Bacellar de Mell",
        "Christopher Alan Julian",
        "Cinthia Moreira Pfannemuller",
        "Clara Maria Hernández Loyola",
        "Claudia Sant'Ana Fuckner Tagawa",
        "Cleide Pereira Martins",
        "Cleidilene Pinheiro da Fonseca",
        "Conceição Marona Oliveira",
        "Cremilda Santos de Almeida Oliveira",
        "Creuza Maria Custódio",
        "Cristiane Medeiros Vallejo de Oliveira",
        "Dagmar Lima Baptista de Brito",
        "Daniel Acácio Moore",
        "Daniel de Oliveira Atala",
        "Daniel Manuel Rey Fernandes",
        "Daniel Martins de Paula",
        "Daniel Pfannemuller",
        "Daniella D'Afonseca e Silva",
        "Davi Livingstone Miranda Almeida",
        "Debora Anjos de Oliveira Atala",
        "Debora Sant'Ana Fuckner Clementino",
        "Derci Pinheiro Junqui",
        "Djalma Araujo Nogueira",
        "Edna Volúzia Mourão Benchaya",
        "Edneide Vieira Silva Remigio",
        "Elcia Maria Bernardes Neves da Silva",
        "Eliana Mary M de Paula",
        "Eliane Vidra Pires Corrêa",
        "Elienai Vieira Silva Remigio",
        "Elisabete Garcia Marcelino",
        "Elizabeth Mazzarella",
        "Elizabeth Peixoto Peticov",
        "Elmidia Ferreira do Valle Traldi",
        "Emiko Zakimi Kakuta",
        "Emirson Justino da Silva",
        "Enilda da Silva Gomes",
        "Érica Elaine de Camargo Lara",
        "Erika Pereira Mattos Fiedler",
        "Esther Queiroz de Siqueira",
        "Eunice Vidra",
        "Evandro Reis Neves da Silva",
        "Evandro Reis Neves da Silva Junior",
        "Evanice Conceição Lahoz Audician",
        "Ezedequias Vieira Torres",
        "Ezir Detimermane Nguyen",
        "Fabio Caleffi",
        "Fátima Agnello Martins",
        "Fausto dos Santos Gomes",
        "Felipe Figueiredo da Costa",
        "Fernanda Martins de Oliveira Dolci",
        "Fernanda Silva Guasti",
        "Fernanda Vannini Neves",
        "Fernando Augusto Hocevar",
        "Filipe Bernardes Neves",
        "Filipe Julles Benites Schildt",
        "Flávia D'Afonseca e Silva",
        "Fortunato Raymundo de Oliveira",
        "Francisca Araujo Brettones",
        "Francisco Júnior de Queiroz",
        "Gabriel Aleixo",
        "George Sobrinho",
        "Gina Corsi Amoroso",
        "Giovana de Braga Pacheco Novaes",
        "Giselda Maria da Silva Schildt",
        "Givaldo dos Santos",
        "Gláucia Elisa Alfeo Reis",
        "Glauco Pereira de Oliveira",
        "Graziella de Paula",
        "Gustavo Antonio Chaves Faustino",
        "Gustavo Urdan Moreira",
        "Helio dos Santos Silva",
        "Hélio Fujimoto",
        "Henrique Sant'Ana da Fonseca",
        "Heredie José Lourenço Cruz",
        "Hildalva Domitilde dos Santos",
        "Idê Rosa de Almeida Lima",
        "Igilzeda Oliveira de Araujo",
        "Ilana Bispo dos Santos",
        "Ineide de Souza Queiroga",
        "Isabel Carneiro Carvalho de Souza",
        "Isabelle Cristina Alfeo Reis",
        "Ivanilda de Seta Patta",
        "Yvone de Jesus Guerra Reis",
        "Izabel Borges da Silva",
        "Jacy Ferreira Cirino Pereira",
        "Jairo da Silva Caldas",
        "Jeane Soo Mei So",
        "João Aparecido de Souza",
        "João Baptista Bacellar de Mello",
        "João Batista de Paula Neto",
        "João Gil Gomes",
        "Joaquim Reis Pinto",
        "Joaquina Marques Rodrigues",
        "Joelma Maria de Alencar Nogueira",
        "John Robert Moore Junior",
        "Johnston Viana da Silva",
        "Jonas Pereira de Souza",
        "Jônatas Corrêa Jacob",
        "Joquebede Saldanha Neves",
        "Jorge Kakuta",
        "José Antônio da Silva Pereira",
        "José Assis Moura de Queiroga",
        "José Brettones Junior",
        "José Carlos Fuckner",
        "José Carlos de Oliveira",
        "José Carlos Riegel",
        "Suzi Josefina Conceição Melo Toledo Costa",
        "Josélia dos Santos Almeida",
        "Josélia Gomes da ROCHA",
        "Joselita Oliveira de Araújo",
        "Joubert José Gomes",
        "Joubert José Gomes Junior",
        "Joventina Maria da Conceição Souza",
        "Jovita Santos da Cruz",
        "Juliana Corrêa Jacob Cordeiro da Fonseca",
        "Juliana Hellen Sudano",
        "Julieta de Martino Nunes",
        "Jurema Farina Cardoso Esteves",
        "Juvenal Rodrigues",
        "Kalyane Dias Ferreira",
        "Kamila Ricchiero Cardoso",
        "Karen Maeda",
        "Karen Mora Veríssimo",
        "Karin Pfannemuller Gomes",
        "Kiyomi Tagawa",
        "Larissa do Nascimento Rocha",
        "Leandro Bernardes Neves",
        "Leda Calheiros Teixeira",
        "Leopoldina Conga de Oliveira Vital",
        "Lilian Tagawa",
        "Lindinalva de Almeida Torres",
        "Litercílio Ribeiro dos Santos",
        "Loide Albernaz de Carvalho",
        "Lucas Jalles Benites Schildt",
        "Luciana Souza da Silva",
        "Luciane Ribeiro da Silva Moreia",
        "Luis Henrique Moraes de Souza",
        "Luz Marina Gonçalves de Araújo",
        "Luzia Furuzawa Tagawa",
        "Maciste Siqueira Saldanha",
        "Magna Santana Melo",
        "Manoela dos Santos Sobrinho",
        "Marcelo Alves de Novaes",
        "Marcelo Balian",
        "Marcelo de Carvalho Carvalhaes",
        "Marcia Aparecida de Souza Lopes",
        "Marcia Oliveira Saunitti",
        "Marcos Pinho da Silva",
        "Maria Aldorina Alves Pereira",
        "Maria Alessandra Caleffi",
        "Maria Alice Moraes Monteiro",
        "Maria Ana da Silva",
        "Maria Aparecida Arruda Camargo",
        "Maria Cristina Siriani",
        "Maria da Conceição Sudano",
        "Maria da Glória Barboza",
        "Maria das Graças Souza",
        "Maria de Fátima da Silva",
        "Maria de Lourdes de Assis Moraes",
        "Maria de Lourdes Peterle",
        "Maria Ester de Azevedo",
        "Maria Gorete Pereira Leite",
        "Maria Helena de Souza",
        "Maria Isabel Cardoso Sousa Guerra",
        "Maria José Gomes da Silva",
        "Maria Kelly Gomes Pereira",
        "Maria Lucia Gomes Isac",
        "Maria Luisa Felicio Pereira",
        "Maria Therezinha Graner Vieira",
        "Mariana de Souza",
        "Marina Redekop Cassapian",
        "Marisa Oliveira Santana",
        "Mariza Andrade Santana",
        "Marli Forattore Pfannemuller",
        "Marta Maria Ferro Gomes",
        "Martha da Silva Ferreira Fujimoto",
        "Matheus Barsan Pacilio",
        "Melody Allen Julian",
        "Michelle Aparecida Saunitti",
        "Miguel Luiz Morad Noronha",
        "Milton Maximiano de Brito",
        "Milton Pereira Brito",
        "Mirtes Roberta de Brito",
        "Moisés Calixto Isac",
        "Monica Moreira Rodrigues",
        "Nadejda Kairiak Moroz",
        "Nancy Facchini de Almeida Castro",
        "Natalia do Valle Traldi Lima",
        "Natasha Mora Veríssimo",
        "Neide Borges de Souza",
        "Neidmar Alves de Oliveira",
        "Nelsina Sciré",
        "Neusa Garcia Pereira",
        "Neusa Maria de Miranda Silva",
        "Neusa Maria Reis Cruz",
        "Nguyen Huu Tung",
        "Nilson Mascarenhas da Fonseca",
        "Ninnyane Gomes Leal",
        "Noé Ricardo da Silva",
        "Odilon da Silva Gomes",
        "Oneide Teixeira Corrêa Jacob",
        "Oscar Fernando Simonsen Aldunate",
        "Patricia Albernaz Carvalho Mayorga Amorim",
        "Patricia Mello Garrido Ishida",
        "Patrícia Sobrinho Ries",
        "Paula Almeida Fadigas Cruz",
        "Paula Regina de Sousa Forattore",
        "Paulo Victor Alfeo Reis",
        "Pedro Antonio Ferreira Filho",
        "Pedro Henrique Cardoso Guerra",
        "Pedro Pereira Guerra",
        "Pedro Saunitti Neto",
        "Plínio Cesar Camargo Bacellar de Mello",
        "Priscilla dos Santos Nogueira",
        "Rachel Lynne Julian",
        "Rafael Gomes Maitino",
        "Rafael Leonel Gomes",
        "Raquel Kinoshita Sano",
        "Racquel Patta",
        "Ramon Guimarães Caldas de Souza",
        "Rebeca Corrêa Balian",
        "Rebeca Silva Lima",
        "Regina Fam Moura",
        "Regina Ruggeri Faustino",
        "Remo Carriel P Franco",
        "Renata Assumpção Rodrigues",
        "Renato da Silveira e Silva",
        "Ricardo Bueno de Mello Russo",
        "Ricardo Furtunato de Oliveira",
        "Ricardo Gomes Maitino",
        "Rita de Cácia Cosmo de Souza",
        "Rivas Lopes Bretones",
        "Roberto de Oliveira Frederico",
        "Roberto Vidra",
        "Romilda Costa de Souza",
        "Ronaldo de Souza Queiroga",
        "Rosa Coutinho da Rocha Oliveira",
        "Rosa Karasek Vidra",
        "Rosildo da Silva Lima -",
        "Rosimeire Santos do Carmo",
        "Salviano Manoel do Nascimento",
        "Sandra G Maraviglia Pereira",
        "Sandra Priscila de Oliveira Moreno",
        "Sandra Regina Costa Oliveira Traldi",
        "Sandra Simone D´Afonseca e Silva",
    "Sarah Bretones de Paula",
    "Saulo Rafael de Oliveira",
    "Sérgio Audician",
    "Sérgio Ricardo dos Reis",
    "Severina Herminia Silva",
    "Sharon Lopes",
    "Sheila Terezinha Graziano Yamada",
    "Silvana Peralta Ceravolo",
    "Silvia Aguilar Toro Justino da Silva",
    "Sofia Miguel Elias Rio",
    "Solange Maria Fernandes Riegel",
    "Sônia Flávia Dias Moreira",
    "Stefano Emilio Caleffi",
    "Tarcilio Teixeira dos Santos",
    "Tássio Felipe Silva",
    "Terezinha Galvão",
    "Thatiana Almeida Fadigas Moita",
    "Thiago Augusto Camargo Bacellar de Mello",
    "Thiago Henrique Borges da Silva",
    "Thiago Macedo Moreno",
    "Tiago Roberto Gava",
    "Valdelice Theodoro Santos",
    "Valdir Luís Gil",
    "Valter Aureliano Pereira",
    "Valter Ernandes Rodrigues",
    "Vanessa Barsan Pacilio",
    "Vanessa de Albuquerque Sá Lobo",
    "Vanete Gomes de Oliveira",
    "Vera Regina Lucci Camps Frederico",
    "Veronica Neri Muniz e Silva",
    "Verônica Silva Moitinho",
    "Victor Bernardes Neves",
    "Victor D'Afonseca e Silva",
    "Victor Sciré Queiróz",
    "Vinícius Pinheiro Junqui",
    "Wagner Alex Fiedler",
    "Walter Pfannemuller",
    "Wegton do Nascimento",
    "Wellington Meneses Lobo",
    "Wendel Almeida Torres",
    "Wesley Alan Julian",
    "Yara D'Andrea Soares",
    "Yone Eititus Xavier Colaneri",
    "Yvonne Pereira Augusto",
    "Zacharias Albernaz de Carvalho",
    "Zuleide Siqueira Voutsopoulos",
    "Aurea Lúcia Grimmer Lisboa",
    "Ricardo Neiva Trigo Moreira",
    "Felipe dos Santos Nogueira",
    "Maria da Consolação Reis Pinto",
    "Estela Maris Assumpção Rodrigues",
    "Ricardo Alberto Silva",
    "Lúcia Lemes Silva",
    "Mirella Mendonça Feitosa",
    "Luiz Felippe Santos Cavalcanti",
    "Patricia Delgado Santos Cavalcanti",
    "Regina de Assis Ertel",
    "Sérgio Domingos Veber",
    "Carlos Eduardo da Silva Souza",
    "Robson Almeida Cerqueira",
    "Cristina de Jesus Marin Costa",
    "José Benjamim Ferreira de Souza",
    "Eloina Sampaio de Souza",
    "Laryssa Sampaio de Souza",
    "Jackson Fonteles de Souza (Pr.)",
    "Héllade Aquino Machado Fonteles de Souza",
    "Rebeca Fonteles de Souza",
    "Maria Gisélia Brito de Souza",
    "Rodrigo da Silva Lima",
    "Simone Ribeiro Oliveira Lima",
    "Jefferson Marinho da Silva",
    "Antônio Amaro dos Santos",
    "Cleuza Gonçalves de Oliveira",
    "Elen Karina de Bem Marcelino",
    "Margarete Pereira de Menezes",
    "Mércia Maria Cerqueira Carvalho de Lima",
    "Júlio Dutra Barroso",
    "Essy Campelo Barroso",
    "Joselita Silva Santos",
    "Aldenir Pimentel",
    "Darllany Alves da Cruz",
    "João Pedro Brasolin Facury",
    "Maria Alves Damasceno",
    "Danielle Santos",
    "Olympio de Menezes Neto",
    "Reginaldo Pires Moreira",
    "Zidrone Liebich Moreira",
    "Gilberto Rosa",
    "Rosilene Campos ROSA",
    "Alice Toshie Doi",
    "Priscila Xambre Killing",
    "Lucas Brasolin Facury",
    "Carlos Eduardo Prates Montoro Fagundes",
    "José Mamede Montini",
    "Estela Doblas de Castro Montini",
    "Marta Pereira Mairinque Sant'ana",
    "Maria José Pereira Mairinque",
    "Rogério Alves de SANT'ANA",
    "Gideon Muniz e Silva",
    "Djanilson da Silva Gonçalves",
    "Dalva Maria D'Afonseca e Silva",
    "Antonio Reis Filho",
    "Luciana Souza de Amorim",
    "Ijosiene Jesus Oliveira",
    "Álvaro Frederico Conrado Pompéia",
    "Thais Alves de Sousa",
    "Diana Dias Oliveira",
    "Allana de Oliveira Queiroga",
    "Marcelo Grassi de Abreu",
    "Ocinéia Simões Antunes Crepaldi",
    "Victória Fernandes",
    "Laura Izabel da Silva Santos",
    "Luana Izabel da Silva Santos",
    "Leonardo Correia da Silva",
    "Leandro dos Santos Gomes",
    "Maria Socorro Cavalcante de Matos",
    "Lucélia de Andrade Lima da Silva",
    "Gilson Rosa",
    "Uilson Rodrigo Linguanoto",
    "Daniela C. Fallo de Andrade Linguanoto",
    "Eduardo Rodrigues",
    "Ester de Souza Rodrigues",
    "Rebeca de Souza Rodrigues",
    "Rossini Pereira Leite Junior",
    "Maria Iracema Mesquita de Camargo Neves",
    "Pedro Soares Pinto",
    "Madagaspar Matos de La Rosa",
    "Élcio Montoro Fagundes Fagundes",
    "Jacira Prates Montoro Facury",
    "Alfredo Lamb Killing",
    "Clarice de Jesus Xambre Killing",
    "Samuel Xambre Killing",
    "Kátia de Oliveira da Silva",
    "Rildo Rogério Costa de Freitas",
    "Thais Navarro Mondini",
    "Ana Bela Correia Antunes",
    "Mariana dos Santos Prates",
    "Maithê de Souza Rodrigues",
    "Aida Vieira Silva Remigio",
    "Paloma Maria da Silva",
    "Leticia Borges de Sousa Nunes",
    "Rodrigo Leal da Silveira",
    "Sarah Maria Realti",
    "Marcos Araújo Torres de Paula",
    "Lorena Melo Torres de Paula",
    "Weyden Padilha Cavalcante",
    "Thais Pereira da Silva",
    "Taiz Neto Asakura",
    "Uerlis Santos dos Reis de Oliveira",
    "Carolina Cristina dos Reis de Oliveira",
    "Mauro Cesar Guedes Vicente",
    "Gabriela Maria Nascimento Guedes",
    "Alexandre Barretti",
    "Mary Anne Keila Leocárdio Hocevar",
    "Lucélia",
    "Maria Carmelita da Silva",
    "Antônio de Souza",
    "Lucas de Souza Cristo",
    "Sylvania Coelho Cristo",
    "Angela Maria de Souza Libório Fernandes",
    "Julia Delgado Santos Cavalcanti",
    "Gabriela Fernandes",
    "Mariana Carriel Pinheiro Franco",
    "Djanildo Silva Gonçalves",
    "Martielle Silva Gonçalves",
    "Igraine Milene Souza Martins",
    "Eliane Vieitas Prates",
    "Alessandra Weinmann dos Santos",
    "Emerson Alves da Silva",
    "Sérgio Ricardo de Souza",
    "Loraine Cristine dos Santos Visolli",
    "Carmen Conde",
    "Railde Lima ALVES",
    "Glória Alexandra Ferreira da Cunha Canedo",
    "Maria Silvia de Oliveira",
    "Monica Sibele Parra",
    "Alexandre Gonçalves de Melo",
    "Graciliano Pereira ALVES",
    "Irene Maria da Silva",
    "Daniel de Camargo Aly",
    "Guilherme de Paula Costa",
    "Gyancarla Peralta Cerávolo",
    "Lucas Alencar Nogueira",
    "Matheus Alencar Nogueira",
    "Paula D'Afonseca e Silva",
    "Jean-Luc Fobe",
    "Lisete Pessoa de Oliveira Fobe",
    "Jean-Luc Antoine Olivier Fobe",
    "Alexander Pereira da Silva",
    "Mara Batista de Carvalho Silva",
    "Aurinina Barros Leal",
    "Marcia Aparecida Leal Vanine Bittencourt",
    "Maria Goreti Leal Vanini Isaac",
    "Daniel Flores Dias Trigo Moreira",
    "Renata Alves de almeida",
    "Arnaldo Gama da Esperança",
    "Neusa Gonçalves Souza Esperança",
    "Florival Cecilia",
    "Wanda Elisa Alfeo",
    "Ana Paula Nardini Ohy Melo",
    "Joseph Benjamin Illya Neiman",
    "Dagoberto de Godoy Penteado Neto",
    "Yan Bruno Silva Santos",
    "Giovana Peralta Cerávolo",
    "Érica de Bem Marcelino",
    "Loenne Ane Rodrigues Maciel",
    "Matheus Nunes Borget",
    "Marlene Marcelino Soares Trancoso",
    "Jônatas da Silva Targino",
    "Talita Albernaz de Carvalho",
    "Benedita Fernandes Barbosa",
    "Luis Rogério Kauvano",
    "Erika Cabral Kauvano",
    "Dallary Alves Mendes",
    "Dalva Maria Rodrigues",
    "Renata Rodrigues Vieira da Silva",
    "Ivanilde Sara Francisco",
    "Michelle Pinheiro Ferreira Soares",
    "Anderson Cabral",
    "Marcella Helena",
    "Erika Mayumi Ito Takata",
    "Peterson Raphael Golfredo",
    "Analisse da Cruz Santos",
    "Laice Teixeira dos Santos",
    "Priscilla Schincariol",
    "Daniel Schincariol",
    "Daniel Matias",
    "Demetrius Fernando de Oliveira",
    "Fausto Augusto Ferro Gomes",
    "Alexandre Tavares de Figueiredo",
    "Eroisa Gaspar de Figueiredo",
    "Roberto Ribeiro Vasconcellos",
    "Eliane de Moraes Cavalcante Vasconcellos",
    "Lourival Costa Ramos",
    "Flora Lobo Costa Ramos",
    "Robison Almeida",
    "Rosária Pacheco de Souza Martins",
    "José Antonio Schincariol",
    "Cristina Marques de Sá",
    "Fátima Maria Mendes Brandão",
    "Rebeca Marcondes Silva de Andrade",
    "Juciara Matos Prates",
    "Vasti Muniz e Silva",
    "José Júlio Soares de Freitas",
    "Gustavo Flores Dias Trigo Moreira",
    "Larissa Oliveira Lisounenko",
    "Daniel Fachini",
    "Luciane suarez",
    "Francisco Eduardo Cavalcante de Barros Leal",
    "Maria Isabel de Sousa Nunes",
    "Fabiano José Oliveira Damasceno",
    "Marília Melo Damasceno",
    "Neli Pedrosa da Silva Melo",
    "André Yagi Cardoso",
    "Carolina Prates Canassa",
    "Cláudia Pereira de Oliveira",
    "Gilson Yamada",
    "Isis Sophie de Amorim Souza",
    "João Vitor Cardoso Guerra",
    "Maria Rosa de Jesus",
    "Juliana Cunha Gonçalves",
    "Júlio César Cerqueira Farias Lima",
    "Luiz Eduardo Cardoso Guerra",
    "Maria Piedade Esperança Barbosa",
    "José Donaldesson Leonel",
    "Elaine Martinez Cardoso Leonel",
    "Camila Virginia Cerqueira Farias Lima",
    "Ranieri da Cruz",
    "Luciana Menacho da Cruz",
    "Dórlia Farina Cardoso",
    "Wérica Melo dos Santos",
    "Ruth Martinez Urbaneja",
    "Lorraine Almeida Torres",
    "Mario Daniel de Souza Bernardes",
    "Viviane Lima de Almeida Bernardes",
    "Bruna Lessi Gregório Reis",
    "Ana Paula Marques de Oliveira",
    "Luiz Fernando Oliveira de Luca",
    "Victoria Gutierrez Bispo Oliveira",
    "Henrique César Sônego",
    "Karina Chagas Louzada",
    "Patricia Paula Mendicino",
    "Thais Miotto Oliveira de Sá",
    "Matheus Henrique Santos de Queiróz",
    "Dalyla Alves Mendes",
    "Claudia Cardoso Anafe",
    "Adriana Coggiola Silveira",
    "Nathália Brasolin Porto",
    "Eunice Morais Freire Vilela",
    "Diva dos Santos",
    "Erivan Gomes Pereira",
    "Evelise de Luca Miranda",
    "Glaucia Aparecida Ventura",
    "Leticia Moreira Custódio",
    "Luiz Alvaro Maluf D'Elboux Guimarães",
    "Osvaldo Alves Oliveira Filho",
    "Hugo Eduardo Urquizo Montes",
    "Vânia Poçam",
    "Joyce Carina da Costa Coelho",
    "Adilmar Oliveira de Avila",
    "Nilma Pescuma de Avila",
    "Matheus Cezar Menino",
    "Carla Marcon Mariano Menino",
    "Tarcisio Santana Ramos",
    "Denise Cartaxo Rolim Ramos",
    "Angela de Avila Fiel Cruz Miranda",
    "Renato Herrmann Basto",
    "Ana Teresa Oliveira da Silva Basto",
    "Camilla Volpon Flório",
    "Jonatas Bazzoli",
    "Samara Carrozzino Cordeiro Faria",
    "Gabriela Bighetti Landini",
    "Cleones Vilela da Silveira",
    "Jovelina Santos da Silveira",
    "Victoria de Amorim Souza",
    "Elze Matos Prates",
    "Clementine Lindquist",
    "Késsia Kênia Fontes Gomes",
    "Nicole Lisounenko",
    "Gustavo George Oliveira Melo",
    "Julia Pfannemuller Gomes",
    "Margareth Gonçalves Alvim de Oliveira Freitas",
    "Luiz Sérgio Landini",
    "Elide Maria Bighetti Landini",
    "Daniel Lima Bezerra",
    "José Jaelson dos Santos Silva",
    "Prissila Letícia Alves de Souza",
    "Evellyn Eduarda Falcão Santana",
    "Marta Maria Cordeiro Santiago",
    "Diego Gomes de Oliveira",
    "Emanoela da Silva Alves Ferreira",
    "Jade Souza de Morais",
    "Cristiane Vallejo",
    "Fernando Corner da Costa",
    "Jociel dos Santos da Silva",
    "José  Henrique  de Andrade Tavares",
    "Marisa de Oliveira Costa",
    "Renan Henrique Lima do Nascimento",
    "Yara Claudino da Silva",
    "Iza Mary Luriko Nagato",
    "André Gentil dos Santos",
    "Lídia Miranda Silva",
    "André Jácomo Ghislandi",
    "Anna Moreira Pfannemuller",
    "Daniel Matos Tejeda",
    "Maria Fernanda Ortiz Quatrucci",
    "Luiz Henrique Fiel Cruz MIRANDA",
    "Luzia Carriel Pinheiro Franco",
    "Daniella Mieko Nisimura",
    "Maria Socorro Cardoso dos Santos",
    "Analzira Nascimento",
    "Caio Ernesto Pachen Loeben",
    "Pedro Paulo de Almeida Bernardes",
    "Anderson Yuji Misuni",
    "Abner Eli Bezerra",
    "Abimael Alves de Jesus ALVES",
    "Josenia Eulalia Cerqueira ALVES",
    "Nathielle Cerqueira Alves",
    "Renata Martins Marino",
    "Kelly Cristine Hirosse Marques Oliveira",
    "Jennifer Lima Almanza Paschen Loeben",
    "Maria Aparecida Brito",
    "Salustiano Neto Lauton Brito",
    "Jose Benedito Pereira Cunha Jr.",
    "Elaine dos Santos CUNHA",
    "Sergio de Oliveira",
    "Denivia Rosa dos Santos Oliveira",
    "Rebeca Santos Oliveira",
    "Nathalie Cerqueira Alves",
    "Juliana Fernandes Carrasco",
    "DORIS EMI Aoshima",
    "Jose Tolloto",
    "Daniela Batista Lopes",
    "Luis Henrique de Santana Junior",
    "Isabel Cristina Pagani Santana",
    "Milton Francisco Guedes Oliveira",
    "Vivian Very Guedes Oliveira",
    "Marcos Gilberto Homem de Mello",
    "Maria de Lourdes Lima Almanza",
    "Mário Fonseca Mendonça de Azevedo",
    "Tiago Gomes de Barros",
    "Salvany Vanessa Siqueira Sales Barros",
    "Patrícia Heliane Fachini",
    "Eulógio Facchini",
    "Adair Gonçalves Facchini",
    "Thereza Guedes Maraia",
    "Gabriela Figueiredo Soares de Santana",
    "Luiz Felipe de Santana",
    "Moisés Torres de Albuquerque",
    "Meyre Vicente de Láias Albuquerque",
    "Samira Fauzi Lutfi",
    "Cintia Barros Kuroiwa",
    "Onivaldo Miranda",
    "Priscila de carvalho",
    "Luciano Faneca da Cunha Gonçalves",
    "Juliana de Almeida Cavalcante da Cunha Gonçalves",
    "Gabriel De Bodt Sivieri",
    "Ana Beatriz de Oliveira Atala",
    "Magda Siqueira da Silva Gagliano",
    "Carlos Roberto Gagliano",
    "Nanci Pescuma Martins",
    "Luciana Ferreira Lima",
    "Luciana Rodriguez Cristalino",
    "Luiz Carlos Oliveira de Almeida Junior",
    "Marcello Daniel Covelli Cristalino",
    "Renata Almeida de Queiroz",
    "Shirley Almanzo",
    "Eduardo Fialho",
    "Ingrid Martins Ferreira Gonçalves",
    "Rúbia Nery Borges",
    "Rossana Silva Neri Borges",
    "Pietra Maria Almeida de Queiroz",
    "Parvin Ebrahim Fischer",
    "Fernanda Gonçalves Silva",
    "Carolina Catapirra Lopes de Oliveira",
    "Luis Augusto Alvares Marino",
    "Marcelino Pereira",
    "Ronaldo Borges de Oliveira",
    "Angélica Constantinides",
    "Silvia Cristina Gualberto Santos Asano",
    "Wellington Alexandre Hideo Asano",
    "Ana Beatriz de Oliveira Atala",
    "Silvia Siqueira de Oliveira",
    "Juliana de Souza Conde",
    "Letícia de Souza Condé",
    "Dalva Santos Guedes Oliveira",
    "Raquel de Souza Condé",
    "Antonio Pedro de Oliveira Neto",
    "Heleni Neide Fosca Coggiola",
    "Igreja Batista do Brooklin",
    "Missão Batista Boas Novas",
    "Igreja Batista de Vila Mariana",
    "Ueber Neves",
    "Cláudia Ferrari Neguishi Neves",
    "Ericsson Cardoso Ruiz",
    "Simone Lemes de Lima Ruiz",
    "Wilma C. F. Lepikson",
    "Herman Fonseca de Mello Lepkson",
    "Joselda Rejane Medrado Ramires",
    "Kares Maria de Araujo",
    "João Gomes dos Santos",
    "Marli de Jesus Barreto dos Santos",
    "Markenson Cenatus",
    "Wanis Cenatus",
    "Cenatus Tilus Wichermana",
    "Mercina Alfred Bien Aime",
    "Dertilus Bien Aime",
    "Davi Sano",
    "Ernestina da Cruz Carvalho",
    "Marlene Munhoz Arisa",
    "Valderez Campelo De Menezes",
    "Gabriela Fachini",
    "Paulo Marcos Del Papa",
    "Rita Halluch Del Papa",
    "Marcelo Musial",
    "Vitor Pagani Volpe",
    "Vinicius De Oliveira",
    "Lucas Gonçalves Silva",
    "Adriana Tamiko Maeda",
    "Maria Lima Santos",
    "Laila Lucie Dia Guimarães",
    "Michele arquino da Silva",
    "Ereneide Maria Da Silva",
    "Custódio Francisco da Silva Junior",
    "IGREJA BATISTA MEMORIA",
    "Noelia Andrade S Lima",
    "FANNY CAICEDO MORETI",
    "Raphael Ferreira Brasilio dos Santos",
    "Caroline Milan Brasilio",
    "Valéria Gentil dos Santos",
    "BRUNA PERCILIA TREVELIN DE LIMA",
    "Ivone S. Pacheco de Oliveira",
    "Terezinha Santos de Farias",
    "Karina Farias dos Santos",
    "CAIO BARROS VENTURI",
    "ALINE AUGUSTA MENDES SAIFI",
    "RICARDO PACHECO",
    "SEBASTIANA ALVES VIANA DE MORAES",
    "THIAGO GIOVANI FRANCISCO VIERIRA",
    "PAMELA DE OLIVEIRA VIEIRA",
    "NATHALIA DO VALE TRALDI LIMA",
    "THIAGO PARRA DE MELO",
    "Gabriel Henrique Lima",
    "JOSUÉ LUCAS RIBEIRO",
    "BEATRIZ STELLA GUEZIO",
    "Dieide da Silva Dias",
    "Camila Ribeiro Da Silva",
    "Alison Kaique Lemes Leite",
    "Tainara Alves Pereira",
    "Milena Taló",
    "Sonia Godoy Cappellaro Cotait",
    "ROSEMITH LOVIS JEUNE CENATUS",
    "Isabela de Almeida Bernardes",
    "João Marcelo de Souza",
    "KYAN GRAZIANO YAMADA",
    "JOSÉ FRANCISCO MIRANDA JR",
    "RAFAEL FIEL CRUZ",
    "CENATUS LOWIS JHAUNE ROSE-MITH",
    "Cenatus Wenes",
    "DUIANA FERREIRA LIMA",
    "FABRICIO DA SILVA L.",
    "GABRIELA PARRA DE MELO",
    "Rebeca Santos Oliveira",
    "SARA DA SILVA COSTA",
    "SARA DA SILVA COSTA.",
    "RAQUEL HALLUCH DEL PAPA",
    "SILVIO FILGUEIRA DE MENEZES",
    "GIVALDO TAVARES COSTA",
    "Andréia Silva Alves Esvicero",
    "ANA VITORIA ISAC PERIN",
    "Jessica de Souza Navarro",
    "ALEXANDRE MUNHOES",
    "MARIA CAROLINA DA SILVA CRUZ",
    "MARIA FERNANDA DE LAIAS ALBURQUERQUE",
    "Arthur Dos Santos Fernandes",
    "GUILHERME VASCONCELOS TOMASSELLI NASO",
    "Eshyla Nicole Aquino Silva",
    "CAUÊ AQUINO DA SILVA",
    "Kauã Rodrigues Marcelino da Silva",
    "Tamires Oliveira Santos",
    "Alex da Silva Santos",
    "Airton Paiva Souza",
    "Aline Lourenço de Jesus",
    "Welitania Ramos Da silva",
    "JOICE ANDRADE TAVARES",
    "Daividson Santos de Jesus",
    "LUIZ MAIKE G ROCHA",
    "Natã Rodrigues Marcelino da Silva",
    "Tarsila Lorraine Gomes de Oliveira",
    "Rafael Pereira da Silva",
    "Edmilson Dos Santos Lima",
    "Cristiane Gomes de Oliveira",
    "Jhonata Antonio da Silva",
    "Joana D´arc Rodrigues da Silva",
    "Tereza Inocencia Da Conceição",
    "Luan Ferreira da Silva",
    "Edna Falcão Costa do Amaral",
    "Jacqueline Santos de Brito Rodrigues",
    "Jeferson Rodrigues Marcelino da Silva",
    "Ricardo Elias do Amaral",
    "Albertina Juvenal de Oliveira",
    "Bianca dos Santos Silva",
    "Breno Reis de Jesus",
    "Daniele da Silva Cunha",
    "Danrlley Alves Cruz",
    "Djalma de Oliveira Santiago",
    "Edilene Vieira Martins",
    "Fabiana  Oliveira Andrade Silva",
    "Fabiano Almeida a Silva",
    "Fernanda Rocha da Silva Gonçalves",
    "Francisco Almeida Silva",
    "Jose Martins",
    "Josefa da Silva Cunha",
    "Josenice de Jesus Antunes",
    "Julia Santos Almeida",
    "Luzia Rodrigues Mariano",
    "Matheus Alves da Cruz",
    "Nathalia Rocha Carvalho",
    "Necivaldo Coelho Silva",
    "Sandra de Souza Cristina Neves",
    "Simão Gonçalves de Castro",
    "Simão Gonçalves de Castro",
    "Sueli Santos Almeida",
    "Zenilda Rocha Barbosa da Silva",
    "Miguel Ferreira Ribeiro",
    "Tamile S . Dos Santos",
    "José Edilson Cavalcante dos Santos",
    "Maria de Lourdes do Nascimento Bento Cavalcante",
    "Francisca Ilenise da Siva Paiva",
    "Cláudia de Souza Lima",
    "Wagner alves de Lima",
    "Rebeca Mendes da Fonseca da Silva",
    "Bruno Cesar Lopes Ramos",
    "Hellen Rose Fortunato almeida  Ramos",
    "Linton Avot de Freitas",
    "Monizze Neves de Freitas",
    "Maria Helena Brinker",
    "Ana Clara Almeida Silva",
    "Maria das Dores da Silva",
    "Yan Jonas C. Santiago",
    "Aline Oliveira da Silva",
    "Danielly Beatris Barros",
    "Beatriz Carolina S. Marquees",
    "Samantha DÁndréa Soós",
    "Marcos Antonio de Oliveira",
    "Thalita Kemyllin Lisboa do Amaral",
    "Viviane Costa Anadão Souza",
    "Elaine Cristina Silva Escames",
    "Paulo Henrique Bologna",
    "Neide Aparecida Bologna",
    "Gabriel Henrique Bologna",
    "Ana Clara Teixeira",
    "Ana Beatriz Arruda Teixeira Bologna",
    "Lucas Rodrigues Maria",
    "Antonio Aparecido Rodrigues Maria",
    "Thaís Rangel Marques Bombonato",
    "Elisanete Silva Lisboa do Amaral",
    "Jymenez de Morais Texeira",
    "Darlan Ribeiro Texeira",
    "Lorena Ferreira de Lima Moura",
    "Igor Silva De Moura",
    "Maria Fernanda Silva e Silva",
    "Evelyn Beatriz Schmidt",
    "James Lima da Silva Schimidt",
    "Juliana Vieira Saldanha",
    "Maria Julia Almeida Leitão",
    "Francisco das Chagas Leitão",
    "Renan Moreno de Souza Leite",
    "Mariana Cruz de Freitas",
    "Elisabete Cristina Reis",
    "Barbara carolina Saggiomo",
    "Dioneia Amaral",
    "Juciane Conceição Santos",
    "Nathalia Carvalho Aromatis Goulart Faria de Morais",
    "Rodrigo Goulart Faria de Morais",
    "Luiza Lessi Reis",
    "Emerson De Almeida Reis Filho",
    "Samanta Cicília de Barros Souza",
    "Ricardo Renzo",
    "Natanael Felissimo da Silva",
    "Miriam Andrade Santos",
    "Edson de Jesus Santos",
    "Maria Isabel Mensdes da Fonseca",
    "Larissa Guimarães Braz",
    "Maria Das Graças dos Santos Dias",
    "Ana Beatriz Pereira Santos de Brito",
    "Thiago Thalisson Lisboa do Amaral",
    "Renata Alves Resende de Miranda",
    "Mariane Souza Brito",
    "Joseph Erold",
    "Antonio Rodrigues Amaral",
    "Eugênio De Oliveira Miranda",
    "Maria Lucia Alexandre da Silva",
    "Antonio Ferreira da Silva",
    "Luiz Vinicius Monteiro Carlos de Oliveira",
    "Yuri Silva Vigira",
    "Eliane Barbosa  Batista Lubas Silva",
    "Edson Lubas Silva",
    "Paulo Henrique de Brito",
    "Vânia Aparecida Batista de Lima",
    "Silvana Souza Barreto",
    "Elvis Bonifácio de Santana",
    "Natália Fernanda da Silva Bonifácio",
    "Daniele A. de Godoy Matos Mendes",
    "Joel Jorge Lima Mendes",
    "Damiana Oliveira de Santana",
    "Lais Bonifácio Santana",
    "Alexandre de Freitas Souza",
    "Alexane Lemos Vilas Boas",
    "Paloma Vilas Boas Souza",
    "Marcos Alves Gonçalves",
    "Mirlene Canatus Iseph",
    "Débora Arcanjo Reis",
    "Clovis Silva dos Reis Junior",
    "Roberto Muniz Ambrósio",
    "Claudia da Silva Muniz Ambrosio",
    "Cenatus Sterline Novencha",
    "Piene Lenize",
    "Daniel Willian Evangelista Gomes",
    "Regina Braz Jens",
    "Armando Texeira Moura Junior",
    "Isabel Cristina Diniz Neri",
    "Franklin Oliveira Melo",
    "Liliane Batista do Amaral Melo",
    "Ralph Silva Neri",
    "Eduardo Ulliana Vieira de Albuquerque",
    "Camila Dytz da Cunha",
    "Luciano alcides da Silva",
    "Antonia Kelen Frota",
    "Bruno Sthefan Bastos Barbosa",
    "Bianca Teófilo Marascalchi",
    "Leiliane Santos de Oliveira Moraes",
    "Fábio Lima Galvão Moraes",
    "Raissa da Silva Couto",
    "Igor Ferreira  Arruda",
    "Catia dos santos Maia",
    "André Henrique Batista Lima",
    "Bruna Vargas Vega Carvalhaes",
    "Valmir Maciel De Lima",
    "Rebeca Sâmella Basso da Silva",
    "João Pedro Morais Leme",
    "Mario Souza Ferro",
    "Maria Rafaela Campos Ferro",
    "Isabella Campos Ferro",
    "Gilmar Mendes Lanes",
    "Aila de Souza Ribeiro Lanes",
    "Thatiany Paixão Rodrigues",
    "Eloá Almeida Silveira",
    "MBU Church",
    "Ana Carolina Souza do Amaral Castellões Cintra",
    "Ana Luiza Neves de Freitas",
    "Marcus Vinícius Soares",
    "Isabela Lessi Reis",
    "Emerson de Almeida Reis Filho",
    "Daniel Loureiro Cintra",
    "Daniel da Silva Muniz Ambrozio",
    "Nicolas Renato Amaral Melo",
    "Wichemana Cenatus Tilus",
    "Laura Melo Torres de Paula",
    "Welder Valsini Calazans Medeiros",
    "Cilene Magalhaes Mediros",
    "Vicentina de Paula Almeida Silva",
    "Izabel Rodrigues de Souza",
    "Giorgio Dallegrave Ricci",
    "Carlito de Jesus Sousa",
    "Gilberto Martins Ramos",
    "Fabiana Barroso",
    "Antonella Barroso Florencio",
    "Márcio Taba Iwayama",
    "Janaina Viana Mesquita",
    "Cindy de Souza Lima",
    "Alda da Cruz Bretones",
    "Terezinha dos Santos",
    "Jorge Alberto Garcia Ortiz",
    "Francy Maria Souza de Ferro",
    "Francy Maria de Souza Ferro",
    "Neusa C Iwama Jordá",
    "Daniel Castilho de Oliveira",
    "Maria de Jesus Pereira Borges Leal",
    "Thales Felipe Santos Pereira",
    "Roselinda Ayres Leal Pereira",
    "Alex Augusto de Castro",
    "Renata Manegatt de Castro",
    "Márcio Vinícius Dias",
    "Renan Oliveira de Souza",
    "Julian Fonseca Carneiro",
    "Neemias Manoel Peck de Wejamba",
    "Anderson Muniz dos Santos",
    "Tiago Arthur Vidoto Jorge",
    "Douglas Ozanan Costa",
    "Carlos Alberto Jorge",
    "Jessica Sant´ana dos Santos",
    "Amanda de Meireles Nunes Dias",
    "Jefferson Silva de Souza",
    "Ana Elisa Gonçalves V Jorge",
    "Joseane Andrade Silva",
    "Lucas Gabriel Paiva",
    "Erich Muniz dos Santos",
    "Isabela Oliveira Moraes",
    "Eliana Almeida Calixto",
    "Brena Xavier de Oliveira",
    "Mariana S. Viana",
    "Jefferson Alves de Souza",
    "Israel Couto",
    "Victória de Miranda Caites Jorge",
    "Fabiana Paixão Da Silva Rodrigues",
    "Thiago Rodrigues Candido",
    "Vicente Oaulo das Virgens Galdino",
    "Antonio Sergio Penha",
    "Debora Tavares Souza Penha",
    "Ana Maria Leandro Serafin",
    "Simone Olegario dos Santos",
    "André do Valle Traldi Lima",
    "Bruno do Valle Traldi Lima",
    "Letícia Souza Ferreira Rocha",
    "Wellington Rocha Barbosa da Silva",
    "Alizete Rodrigues de Santana",
    "Ana Beatriz akani Sumiyo",
    "Denise de Lucema Pontes",
    "José Francisco de Lucena Pontes",
    "Dayane de Souza Nascimento",
    "Marjosy Carvalho da Cunha",
    "Ana Paula da Silva Viana Rodrigues",
    "Maria Isabel Hining Motta",
    "Yulli Amorim Alves",
    "Vitória Alves de Freitas Ferreira",
    "Alan Ferreira Costa da Rocha",
    "Walter Otto Rupp",
    "Sarita San Ana Lazaro Rupp",
    "Andrea Reys",
    "Ester Damares Gonçalves Silva Vedoto Jorge",
    "Gersino da silva",
    "Jorge Vieira dos Santos",
    "Lenivania Reis dos Santos",
    "Maildes Barbosa Santana",
    "Denivaldo Borges da Silva",
    "Eduardo André Vidoto Jorge",
    "Welida de Paula Lima Araújo",
    "Solon",
    "Jacqueline Azevedo Almeida da Silva",
    "Walker de Lima Souza",
    "Marlon Brandon de Jesus Pereira",
    "Isabel Aparecida C Pedrassolli",
    "Mariana Saldanha Viegas Duarte",
    "Rejane Alves Barbosa Henrique da Silva",
    "Jaime Soares Martins",
    "Débora Pfannemuller Gomes",
    "Ednéia Falcão dos Santos",
    "Cleidnar Silva Pereira",
    "Vitoria Steohany Moreira dos Santos",
    "Fernando Mendes da Silva",
    "Janilândia Cavalcante de Almeida",
    "Julia Alexandre da S. Oliveira",
    "Joselita Vieira Santos",
    "Stephanie Cicuto Landim Alves Moreira",
    "José Arimateia Barros",
    "José Maria Branco Furtado",
    "Yanna Sousa Branco Furtado",
    "Helena Vieira Mantanhani",
    "Laura Vieira Montanhani",
    "Isabella Pieroni Alves Raffaelli",
    "Silvia Regina Alves da Cruz",
    "Martin Minski",
    "Wilson Nunes Texeira",
    "Natascha Kammerleithner",
    "Julia Baltazar Rodrigues",
    "Nicolas Vargas Monteiro",
    "Renato Pinheiro de Souza",
    "Fernanda Anselmo de Assis Rocha",
    "Lucia Dinapoli Hototian",
    "Jacques Hototian",
    "Maana Maemy Cenatus",
    "Michelle Batista Sant´anna",
    "Lucas Fachini",
    "Jhonatas Henrique Fernandes de Salles",
    "Vania Sde Souza",
    "Ester Vilas Boas Souza",
    "Ana Carolina Franco Cabral",
    "Rosana Giosa",
    "Lívia Miho Maeda Misuno",
    "Marcela Zanetti Mascarenhas",
    "Diego José Fernandes Cabral",
    "Franklin Davi Amaral Melo",
    "Iris Medeiros de Barros",
    "Alessandro de Freitas Souza",
    "Sara Noemi Segovia Sosa",
    "Juan Vicente Segovia Sanehez",
    "Maria Del Socorro Sosa",
    "Maria Luiza Sant´anna Pinheiro",
    "Antonia Alda de Oliveira",
    "Denise Pinto Caçador",
    "Bruna Rafaela Paiva",
    "Samuel Paiva Ferreira Dias",
    "Francis Guimarães Gama",
    "Henrique Gama",
    "Fernanda Mizukami Loução",
    "Claudio Rafael Cicuto Landim Alves Moreira",
    "Kaylla Teodoro Araujo",
    "Eduardo de Jesus dos Santos",
    "Laura Nicolly Falcão Santana",
    "Josymar Carvalho da Cunha",
    "Jhullia Brito Rodrigues",
    "Vinicius Eduardo Vieira Amaral",
    "Josefa de Almeida Melo",
    "Elisabet Facchini",
    "Renata Cristina Baltazar Rodrigues",
    ]
}
